Homework 2
================
Sarah Vititoe
9/27/2018

Before beginning, let's load in the tidyverse.

``` r
library(tidyverse)
```

    ## ── Attaching packages ──────────────────────────────────────────────────────── tidyverse 1.2.1 ──

    ## ✔ ggplot2 3.0.0     ✔ purrr   0.2.5
    ## ✔ tibble  1.4.2     ✔ dplyr   0.7.6
    ## ✔ tidyr   0.8.1     ✔ stringr 1.3.1
    ## ✔ readr   1.1.1     ✔ forcats 0.3.0

    ## ── Conflicts ─────────────────────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()

### Problem 1: NYC Subways

*"This problem focuses on NYC Transit data; in particular, this CSV file contains information related to each entrance and exit for each subway station in NYC."*

*"Read and clean the data; retain line, station, name, station latitude / longitude, routes served, entry, vending, entrance type, and ADA compliance." *

*"Convert the entry variable from character (YES vs NO) to a logical variable (the ifelse or recode function may be useful)."*

``` r
mta <- read_csv("./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv") %>%
  janitor::clean_names() %>%
  select(line, starts_with("station"), starts_with("route"), 
         entry, entrance_type, vending, ada) %>%
  mutate(entry = ifelse(entry == "YES", TRUE, FALSE))
```

    ## Parsed with column specification:
    ## cols(
    ##   .default = col_character(),
    ##   `Station Latitude` = col_double(),
    ##   `Station Longitude` = col_double(),
    ##   Route8 = col_integer(),
    ##   Route9 = col_integer(),
    ##   Route10 = col_integer(),
    ##   Route11 = col_integer(),
    ##   ADA = col_logical(),
    ##   `Free Crossover` = col_logical(),
    ##   `Entrance Latitude` = col_double(),
    ##   `Entrance Longitude` = col_double()
    ## )

    ## See spec(...) for full column specifications.

In the code above, I read in my file name using the read\_csv function. I piped my result into the janitor package, which helps me clean up the names a bit. Then, I selected the variables we were interested in. We have the line, information about the station (it's name, latitude, and longitude), all of the routes served by the station, a logical variable that tells us whether there is an entrance (as opposed to just an exit), what the entrance type is (e.g. stairs, or terrifying elevator on 168th), and whether than entrance is ADA compliant. I had to coerce the entry variable to be logical, by using an ifelse statement. We have 20 columns and 1868 rows in our tibble. This dataset is definitely not tidy, since we have a ton of rows with the different routes spread out in various columns.

*"How many distinct stations are there? Note that stations are identified both by name and by line (e.g. 125th St A/B/C/D; 125st 1; 125st 4/5); the distinct function may be useful here."*

``` r
mta %>%
  group_by(line, station_name) %>%
  n_distinct()
```

    ## [1] 684

We have 684 unique stations.

*"How many stations are ADA compliant?"*

``` r
mta %>% 
  select(line, station_name, ada) %>%
  group_by(line, station_name) %>%
  filter(ada == TRUE) %>% 
  n_distinct() 
```

    ## [1] 84

Only 84 of those stations are ADA compliant. :(

*"What proportion of station entrances / exits without vending allow entrance?"*"

``` r
mta %>%
  filter(vending == "NO") %>% 
  select(line, station_name, entry) %>% 
  distinct() %>% 
  summarise(proportion = mean(entry)) %>%
  knitr::kable()
```

|  proportion|
|-----------:|
|   0.3873874|

38.7% of all station etrances without a vending machine allow entrances.

*"Reformat data so that route number and route name are distinct variables."*

``` r
mta <- mta %>%
  gather(key = route_number, value = route_name, starts_with("route")) %>%
  select(line, station_name, route_number, route_name, ada, everything())
```
